# Generated by Django 4.0.4 on 2022-06-25 15:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_issue', models.TextField(blank=True, default='', help_text='Enter a brief description of the problem', max_length=1000)),
                ('vin_codes', models.CharField(help_text='17 Character', max_length=17, unique=True, verbose_name='VIN code')),
                ('num_plate', models.CharField(max_length=6, verbose_name='Number Plate')),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
                'ordering': ['car_brand', 'vin_codes'],
            },
        ),
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='Enter a car manufacturer (e.g. BMW, Ford)', max_length=100, verbose_name='Brand')),
                ('model', models.CharField(help_text='Enter a car model (e.g. F10, Focus)', max_length=100, verbose_name='Model')),
            ],
            options={
                'verbose_name': 'Car Brand',
                'verbose_name_plural': 'Car Brands',
                'ordering': ['brand'],
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, default='', max_length=20, verbose_name='Name')),
                ('last_name', models.CharField(db_index=True, default='', max_length=20, verbose_name='Surname')),
            ],
            options={
                'verbose_name': 'Owner',
                'verbose_name_plural': 'Owners',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50, verbose_name='Job Name')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['job_name'],
            },
        ),
        migrations.CreateModel(
            name='RepairOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='price')),
                ('car_issue', models.TextField(blank=True, null=True, verbose_name='Issue')),
                ('due_back', models.DateField(blank=True, db_index=True, default=datetime.date(2022, 7, 2), null=True, verbose_name='Due back')),
                ('status', models.PositiveIntegerField(choices=[(0, 'New'), (10, 'Accepted'), (20, 'Under repair'), (30, 'Done'), (50, 'Returned')], default=0, verbose_name='Status')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carservice.car', verbose_name='Car')),
                ('car_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='carservice.owner')),
            ],
            options={
                'verbose_name': 'Repair order',
                'verbose_name_plural': 'Repair orders',
                'ordering': ['car_issue'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Price')),
                ('repair_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='carservice.repairorder', verbose_name='Repair Order')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carservice.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Repair job',
                'verbose_name_plural': 'Repair jobs',
                'ordering': ['repair_order'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='car_brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carservice.carbrand', verbose_name='Car brand'),
        ),
    ]
